site_name: Django intro 中文版
site_url: null
repo_url: null
repo_name: django-intro-zh
site_description: Django 官方教程中文版
site_author: 7sDream

site_dir: html/

pages:
- '介绍': ../README.md
- '文档':
    - '初识 Django': glance.md
    - '安装 Django': install.md
    - '第一个 Django 项目 - 第一部分': part1.md
    - '第一个 Django 项目 - 第二部分': part2.md
    - '第一个 Django 项目 - 第三部分': part3.md
    - '第一个 Django 项目 - 第四部分': part4.md
    - '第一个 Django 项目 - 第五部分': part5.md
    - '第一个 Django 项目 - 第六部分': part6.md
    - '编写可重用的应用': reusable_app.md
    - '下一步我该干什么': whats_next.md
    - '为 Django 贡献代码': patch.md

theme: amelia
